### ISSUE TITLE
Possible regression in batch formation speed?

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/snowfall#101]
Some time ago I was getting this:
```2021-02-05 00:32:31,376 INFO [mmi_bigram_train.py:239] batch 270, epoch 0/10 global average objf: 0.806999 over 5352029.0 frames (100.0% kept), current batch average objf: 0.555007 over 19790 frames (100.0% kept) avg time waiting for batch 0.008s```
and now getting this:
```2021-02-17 00:10:20,715 INFO [mmi_bigram_train_reg.py:272] batch 270, epoch 0/10 global average objf: 0.773641 over 7765169.0 frames (100.0% kept), current batch average objf: 0.481149 over 29917 frames (100.0% kept) avg time waiting for batch 0.150s```
... see time waiting for batch.  Is this something to be concerned about?

**Comment by pzelasko** [comment]
Is it possible that there are other processed performing significant I/O operations on your machine? Is this using the current recipe in master or something else? Seems like your batch size is effectively larger by 50% but that shouldn’t make it that slow.

**Comment by danpovey** [comment]
forget this, the time is normal when I try it now..
