### ISSUE TITLE
Lattice rescoring in *_decode.py

### ISSUE THREAD

**Issue by EmreOzkose** [k2-fsa/snowfall#116]
Hello, I trained transformer acoustic model on my dataset. I put existing files to data/lang_nosp. Then all processes are same with [ctc_att_transformer_train.py](https://github.com/k2-fsa/snowfall/blob/master/egs/librispeech/asr/simple_v1/ctc_att_transformer_train.py). As a result, output of ctc_att_transformer_decode.py gives WER %100 because hyps are all empty. When I check lattices, they are similar to text. For example 

Transcription -> berry
Output of decoding -> beerrll

or 

Transcription -> thank you
Output of decoding -> tennkkyyhav

In detail, [get_texts](https://github.com/k2-fsa/snowfall/blob/dbcfe5a127efb245e85fc6044b2f2f0024e24b73/snowfall/common.py#L273) gives empty hyps. 

I think that problem is converting phones to words. At this point, problem might be scoring lattices. Is there any script for rescoring lattices according to a language model?

or what can be the problem?
thanks in advance.

**Comment by danpovey** [comment]
Not sure what you put in lang_nosp, something from an existing Kaldi setup?
I'm afraid we're not yet at the stage where we can easily support people trying to do things like this.
Eventually we'll reorganize the scripts and make things much easier (probably in the 'Icefall' iteration of this
project) but for now things are going to be a little hard to work with.

**Comment by EmreOzkose** [comment]
Thank you for information. Yes, files were taken from an existing Kaldi setup, I am still trying to find the glitch in my setup. It might be files in lang_nosp. I will update the issue if I find something new.
