### ISSUE TITLE
Problem in creating LG

### ISSUE THREAD

**Issue by jimbozhang** [k2-fsa/snowfall#12]
It seems there is a problem during `k2.intersect(L, G)` due to the disambiguation symbols. I'll fix it, if needed.

**Comment by csukuangfj** [comment]
Is the error caused by k2?

**Comment by danpovey** [comment]
No, it's because you prepared L.fst which has no disambiguation symbol
self-loops.
L_disambig.fst has them.
We don't need LG for training of CTC, just L for now.

**Comment by qindazhu** [comment]
@jimbozhang you should sync your local branch with remote master, as @danpovey said, we don't need G in CTC training and we have removed that in latest scripts. Will close this issue.

**Comment by qindazhu** [comment]
mm, found that I have no permission to close issues of this repo.

**Comment by danpovey** [comment]
invited you

**Comment by qindazhu** [comment]
Thanks
