### ISSUE TITLE
Issue in naming: LG vs HLG

### ISSUE THREAD

**Issue by pzelasko** [k2-fsa/snowfall#121]
I was explaining snowfall's approach to decoding to somebody and I realized that what we call "LG" might actually be "HLG", because the actual LG is composed with `ctc_topo` (our `H`); see e.g. in the following contexts:

https://github.com/k2-fsa/snowfall/blob/master/snowfall/decoding/graph.py#L66
https://github.com/k2-fsa/snowfall/blob/master/egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py#L71

If you agree with that I will rename it.

**Comment by csukuangfj** [comment]
How about renaming it to TLG? EESEN calls it TLG.

**Comment by jtrmal** [comment]
Imo TLG would work  -- I was actually about to write it as well.

**Comment by pzelasko** [comment]
What does T standard for? I am not super familiar with EESEN.

**Comment by csukuangfj** [comment]
T represents Token.

**Comment by jtrmal** [comment]
it's a mapping between ctc labels and phonemes, IIRC the definition, so I
think it fits.
y.

**Comment by jtrmal** [comment]
or graphemes (or whatever unit your lexicon is in)

**Comment by pzelasko** [comment]
Thanks. As long as it's explicit that it's something more than LG, it sounds good to me.

**Comment by danpovey** [comment]
I'd rather call it HLG because that's a more widely known terminology.
