### ISSUE TITLE
Recipe for the GigaSpeech corpus

### ISSUE THREAD

**Issue by jimbozhang** [k2-fsa/snowfall#148]
Hey guys, I just got some time to create a k2 recipe for the GigaSpeech corpus. @chenguoguo

Once the recipe ready, I'll make PRs to both GigaSpeech's [repo](https://github.com/SpeechColab/GigaSpeech) and here.

**Comment by pzelasko** [comment]
I would be interested to know if you find some bottleneck in Lhotse - either speed or memory usage. I have a feeling we’ll need to optimize it a bit to make it convenient to use for such large corpora.

**Comment by jimbozhang** [comment]
> I would be interested to know if you find some bottleneck in Lhotse - either speed or memory usage. I have a feeling we’ll need to optimize it a bit to make it convenient to use for such large corpora.

OK, I'll pay attention on it. If there's such bottleneck, I'll try to fix it and make a PR to Lhotse.

**Comment by chenguoguo** [comment]
Great! I planned to work on this but it's great that you have some time for this, one less task for me :-)  I'll start playing with it once we have a basic recipe.

**Comment by dophist** [comment]
@jimbozhang  default GigaSpeech dev/test sets are huge(50+ hours combined).  Dev/Test sets of this large are not necessary for academic-scale research, and it slows down research experiments.  During the development of K2 recipe, if you can draw random subsets(e.g. 2500 utts for dev, and 5000 utts for test) from standard dev/test, we can stabilize your subsets and tag them as something like "GigaSpeech DevSlim/TestSlim", and incorporate these tags into raw GigaSpeech dataset.

**Comment by danpovey** [comment]
Good idea to have a subset.
In k2/snowfall we decode on the GPU and decoding currently takes a couple
minutes on a single GPU (vs. 12 hours for training 10 epochs on 100 hours,
for example),
 think a 10 or 20 hour subset might be reasonable, depending on the WER.
