### ISSUE TITLE
Sampler type mismatch

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/snowfall#153]
Guys,
When experimenting with a particular model type (that used wide context) using mmi_bigram_train.py, I noticed very bad validation prob and also very bad decoding results.  I was able to fix this by modifying the SingleCutSampler used for validation and decode, to BucketingSampler.  This is  just an FYI, that these things can be sensitive to the sampler type for certain kinds of models.
I'll close this issue, it's an FYI.

**Comment by pzelasko** [comment]
Just for me to understand better - the extra padding introduced from collation of different length utterances caused this? That's... interesting.
