### ISSUE TITLE
how to convert LG.aux_labels of type tensor to _k2.RaggedInt

### ISSUE THREAD

**Issue by Jarvan-Wang** [k2-fsa/snowfall#160]
when the LG is read from LG.fst.txt, the aux_labels is type of torch.tensor
but k2.ragged.remove_values_eq(LG.aux_labels, 0) require it to be _k2.RaggedInt

regular LG.aux_labels.values().dim() == 1
the init func of it needs a k2::RaggedShape:
    _k2.RaggedInt(shape: k2::RaggedShape, values: at::Tensor)
and there k2.ragged.create_ragged_shape2 create a 2d raggedshape rather than 1d

p.s.
sometings LG.determinze() return a _k2.RaggedInt sometimes not.

any correct way to convert the type of LG.aux_labels ?

**Comment by csukuangfj** [comment]
Both `k2.RaggedInt` and `torch.Tensor` are called tensors in k2.

`k2.RaggedInt` is just another kind of tensors, i.e., ragged tensors.

---

> any correct way to convert the type of LG.aux_labels ?

What do you want to convert it to?

**Comment by Jarvan-Wang** [comment]
> 
> 
> Both `k2.RaggedInt` and `torch.Tensor` are called tensors in k2.
> 
> `k2.RaggedInt` is just another kind of tensors, i.e., ragged tensors.
> 
> > any correct way to convert the type of LG.aux_labels ?
> 
> What do you want to convert it to?

convert torch.tensor to k2.RaggedInt

another thing, I compiled the latest k2, and clone the latest snowfall.
but they is not compatible with each other.
for example:
```
  File "/search/odin/wangjiawen/espnet2_500h_mmi/espnet2/bin/mmi_asr_inference.py", line 194, in inference
    ctc_topo = k2.arc_sort(build_ctc_topo(phone_ids_with_blank))
  File "/search/odin/wangjiawen/espnet2_500h_mmi/snowfall/training/ctc_graph.py", line 40, in build_ctc_topo
    ans = k2.Fsa.from_str(arcs, num_aux_labels=1)
TypeError: from_str() got an unexpected keyword argument 'num_aux_labels'
```
could you provides any working combinations of them?

**Comment by csukuangfj** [comment]
> convert torch.tensor to k2.RaggedInt

That is doable, provided you have a `k2.RaggedShape` for that `torch.Tensor`.

> the init func of it needs a k2::RaggedShape:
_k2.RaggedInt(shape: k2::RaggedShape, values: at::Tensor)

That is what you need if you have `k2.RaggedShape`.

**Comment by Jarvan-Wang** [comment]
> 
> 
> > convert torch.tensor to k2.RaggedInt
> 
> That is doable, provided you have a `k2.RaggedShape` for that `torch.Tensor`.
> 
> > the init func of it needs a k2::RaggedShape:
> > _k2.RaggedInt(shape: k2::RaggedShape, values: at::Tensor)
> 
> That is what you need if you have `k2.RaggedShape`.

I know I need a k2.RaggedShape of LG.aux_labels

Could you provide a demo code to make 
    LG.aux_labels of type torch.tensor
go through this:
    k2.ragged.remove_values_eq(LG.aux_labels, 0)

**Comment by csukuangfj** [comment]
> I know I need a k2.RaggedShape of LG.aux_labels

To get the ragged shape of `LG.aux_labels`, you can use `LG.aux_labels.shape()`.

---

> Could you provide a demo code to make
LG.aux_labels of type torch.tensor

You can use `LG.aux_labels.values()`, which returns a 1-D torch.Tensor.

You can find some demos in the test code of k2, such as
- https://github.com/k2-fsa/k2/blob/c4cf11dbd402b147ae8fb5049ae9040aeccc5ef4/k2/python/tests/ragged_test.py#L25

**Comment by csukuangfj** [comment]
We are planning to write more tutorials about k2. Hopefully, that will help you to understand and
use APIs related to ragged tensors of k2.

**Comment by Jarvan-Wang** [comment]
The reason why sometimes LG.aux_labels is of type _k2.RaggedInt, sometimes of type torch.tensor after LG.determinze() is that:
```
def determinize(fsa: Fsa) -> Fsa:
    assert fsa.is_cpu()
    assert fsa.requires_grad is False
    # when fsa is already determinzed, then the orig fsa will be returned without change
    if fsa.properties & fsa_properties.ARC_SORTED_AND_DETERMINISTIC != 0:  # noqa
        return fsa

    ragged_arc, arc_map = _k2.determinize(fsa.arcs)
    # the out_fsa.aux_labels is of type _k2.RaggedInt
    out_fsa = k2.utils.fsa_from_unary_function_ragged(fsa, ragged_arc, arc_map)
    return out_fsa
```
solution is to give a undetermized LG or comment the "if" above
then a LG whose aux_labels is of type _k2.RaggedInt is obtained
