### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by zhichaowang** [k2-fsa/snowfall#168]
Hi, guys,

     I'm following steps in https://k2.readthedocs.io/en/latest/installation.html to install k2 from source, but got an error when 
"make _k2":
===========================================================================
[ 32%] Building CUDA object k2/csrc/CMakeFiles/context.dir/algorithms.cu.o
k2/k2/csrc/ragged.h: In member function 'k2::Ragged<k2::Any>& k2::Ragged<T>::Generic() const':
k2/k2/csrc/ragged.h:402:8: error: binding reference of type 'k2::Ragged<k2::Any>&' to 'const k2::Ragged<k2::Any>' discards qualifiers
     return *reinterpret_cast<const Ragged<Any>*>(this);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
make[3]: *** [k2/csrc/CMakeFiles/context.dir/build.make:63: k2/csrc/CMakeFiles/context.dir/algorithms.cu.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:1772: k2/csrc/CMakeFiles/context.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3326: k2/python/csrc/CMakeFiles/_k2.dir/rule] Error 2
make: *** [Makefile:1156: _k2] Error 2
============================================================================

Has anyone seen this error before?

**Comment by csukuangfj** [comment]
@zhichaowang 
Thanks for reporting.

Please pull the latest k2. That was an error fixed a minute ago in 
https://github.com/k2-fsa/k2/pull/724

**Comment by zhichaowang** [comment]
> @zhichaowang
> Thanks for reporting.
> 
> Please pull the latest k2. That was an error fixed a minute ago in
> [k2-fsa/k2#724](https://github.com/k2-fsa/k2/pull/724)

Works! Thank you!

**Comment by zhichaowang** [comment]
closed!
