### ISSUE TITLE
ImportError: libc10.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kakushawn** [k2-fsa/snowfall#21]
Hi, I tried to run the sample but after installing k2 I got this error:
> python
```Python 3.7.9 (default, Aug 18 2020, 06:22:45) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import k2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shawn/repos/snowfall/egs/librispeech/asr/simple_v1/.k2_simple_v1/lib/python3.7/site-packages/k2/__init__.py", line 1, in <module>
    from .autograd import get_tot_scores
  File "/home/shawn/repos/snowfall/egs/librispeech/asr/simple_v1/.k2_simple_v1/lib/python3.7/site-packages/k2/autograd.py", line 6, in <module>
    import _k2
ImportError: libc10.so: cannot open shared object file: No such file or directory
```
--
> pip list
```
Package           Version
----------------- ------------
beautifulsoup4    4.9.3
cached-property   1.5.2
cffi              1.14.3
click             7.1.2
cytoolz           0.11.0
dataclasses       0.6
future            0.18.2
graphviz          0.15
h5py              3.1.0
k2                0.1
lhotse            0.1.1
lilcom            1.1.0
numpy             1.19.4
pandas            1.1.4
pip               20.2.4
pycparser         2.20
python-dateutil   2.8.1
pytz              2020.4
PyYAML            5.3.1
setuptools        47.1.0
six               1.15.0
SoundFile         0.10.3.post1
soupsieve         2.0.1
sphfile           1.0.3
toolz             0.11.1
torch             1.7.0
torchaudio        0.7.0
typing-extensions 3.7.4.3
wheel             0.35.1
```

Can you help me fix this?
Thanks!

**Comment by csukuangfj** [comment]
Please run

```
import torch
import k2
```

`torch` should be imported first.

**Comment by csukuangfj** [comment]
Will update the pip package on PyPI.

**Comment by csukuangfj** [comment]
Closing.

Please try the latest k2 on PyPI, e.g.,

```bash
pip install k2==0.1.1.dev20201118
```

**Comment by lianrzh** [comment]
> Closing.
> 
> Please try the latest k2 on PyPI, e.g.,
> 
> ```shell
> pip install k2==0.1.1.dev20201118
> ```

@csukuangfj i install the latest k2 like this, but it is wrong.

`
>>> import torch
>>> import k2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/app/anaconda3/envs/k2/lib/python3.7/site-packages/k2/__init__.py", line 1, in <module>
    from .autograd import get_tot_scores
  File "/data/app/anaconda3/envs/k2/lib/python3.7/site-packages/k2/autograd.py", line 7, in <module>
    import _k2
ModuleNotFoundError: No module named '_k2'

`

**Comment by csukuangfj** [comment]
Is there a file `_k2.cpython-37m-x86_64-linux-gnu.so` located in
`/data/app/anaconda3/envs/k2/lib/python3.7/site-packages/`?

The packages on PyPI is not the latest. Could you refer to
https://github.com/k2-fsa/k2/blob/master/INSTALL.md to install k2?

---

The most convenient way to install the latest k2 from pre-built wheel packages is to go to
https://github.com/k2-fsa/k2/actions/runs/384661541
and select the one that is best suitable for you system.
