### ISSUE TITLE
Test results at multiple LM scales, picking best

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/snowfall#211]
Can we change the decoding script to test the results with multiple LM scales, say, 0.7 through 1.2 for now?

We already have the property 'lm_scores' on the lattices which dictates the LM part of the scores. (although 'scores' also contains the original acoustic scores plus the LM scores).  
We could clone the 'scores' array, and then repeatedly assign:
  `lats.scores = scores + lats.lm_scores * (lm_scale - 1.0)`
and then get the best paths again.
We will have to check that assigning to the 'scores' property in k2 properly invalidates the forward and backward
scores that are cached in the Fsa, otherwise all output will be the same.

For now let's just always output the WERs from each scale, and also a line that says "best WER" for each test set, so we can easily grep for it.

**Comment by csukuangfj** [comment]
ok, I am making the changes.
