### ISSUE TITLE
compute_and_store_features() got an unexpected keyword argument 'augment_fn' 

### ISSUE THREAD

**Issue by lvchigo** [k2-fsa/snowfall#22]
- hi; when i use mini_librispeech dataset and change dataset path, the error coming...

pip list:
python                  3.7
torch                     1.6.0+cu101
torchaudio            0.6.0
torchvision            0.7.0+cu101
lhotse                    0.1.1
k2                          0.1

![1](https://user-images.githubusercontent.com/8186051/99513853-0b03e480-29c6-11eb-9c23-a60535c30948.png)

**Comment by qindazhu** [comment]
what are the `dev-clean-3` and `train-clean-5` here? can you try to run with the original script to see if you get the same error? I mean, just clone the repo and don't change any code in it.

**Comment by danpovey** [comment]
Maybe it was a change in lhotse interface and we need to change our code.

**Comment by qindazhu** [comment]
Not sure, will check

**Comment by qindazhu** [comment]
OK, it should be `augmenter` with pip package `lhotse 0.1.1`,
```
CutSet.compute_and_store_features.__code__.co_varnames
('self', 'extractor', 'storage', 'augmenter', 'executor', 'mix_eagerly', 'futures', 'cut', 'cut_set')
```
but in master branch of lhotse, it now is `augment_fn`
```
>>> lhotse.CutSet.compute_and_store_features.__code__.co_varnames
('self', 'extractor', 'storage', 'augment_fn', 'executor', 'mix_eagerly', 'futures', 'cut', 'cut_set')

```
https://github.com/lhotse-speech/lhotse/blob/2167c774383b815dc0929e9cc6bb7d26eec0fccb/lhotse/cut.py#L325

@pzelasko can you update pip package of lhotse?

@lvchigo for now, you can just do 
```
git clone https://github.com/lhotse-speech/lhotse
cd lhotse
pip install -e '.[dev]'
```
to install lhotse from local src (don't forget uninstall your previous version)

**Comment by pzelasko** [comment]
OK I’ll release a new Lhotse version. Was waiting to accumulate some changes first. BTW Did you guys figure out how to auto-upload nightly builds to pip?

**Comment by jtrmal** [comment]
I had something that might be usefulset up here:
https://github.com/sequitur-g2p/sequitur-g2p/blob/master/.travis.yml

(it's not automatic daily, it needs a tag, but you could tag automatically,
I guess)
y.

**Comment by lvchigo** [comment]
- thank you guys... it's worked... 

- 1. uninstall lhotse 0.1.1
- 2. install lhotse 0.2.1
- final pip list:
python 3.7
torch 1.6.0+cu101
torchaudio 0.6.0
torchvision 0.7.0+cu101
lhotse 0.2.1
k2 0.1

**Comment by danpovey** [comment]
RE automatic builds that upload to pip, I think @csukuangfj might be able to comment.
I believe there we have some kind of automated build but currently only uploads artifacts to github, not pip which would require password.

**Comment by csukuangfj** [comment]
GitHub actions support uploading wheels to PyPI. As for the password, it can be saved in the settings of your account and be accessed in GitHub actions as environment variables. Others can only see the name of the environment variables,  but not their values.  So the username and password can still be kept as secrets.

GitHub actions can be triggered by some events, e.g., on the creation of a tag, on a new pull request, on a merge into a specific branch, at some specified time points per day etc.



Sent from myMail for iOS


Thursday, 19 November 2020, 11:20 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by pzelasko** [comment]
Thanks! I’ll check it out at some point and set it up.
