### ISSUE TITLE
Lexicon only decoding question

### ISSUE THREAD

**Issue by alucassch** [k2-fsa/snowfall#241]
Is it possible to use k2 to decode a character based CTC model with a specific set of words in a lexicon? 

I mean, how do I compose only the L (lexicon) with H (ctc_topo) but without G (the language model) to create the decode lattice with  k2.intersect_dense_pruned?

```python
lattices = k2.intersect_dense_pruned(HL, dense_fsa_vec, 20.0, 8, 30, 10000)
```

**Comment by csukuangfj** [comment]
Please refer to https://github.com/k2-fsa/snowfall/blob/master/snowfall/decoding/graph.py
for how HLG is generated.
To reuse the code, you can use a unigram G, which we do provide code to build that (see
https://github.com/k2-fsa/snowfall/blob/45898f70e3982a47a6fb831c6bb46d5acec9aaf2/snowfall/training/mmi_graph.py#L44)
