### ISSUE TITLE
Subsampling

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/snowfall#25]
We need to modify model.py so it does 3-fold subsampling.  This will increase the speed around 3x (currently mostly in graph stuff).
We may need to change how we create the DenseFsaVec object, so that it takes the subsampling into account when looking at the lengths of the supervised segments.

**Comment by jtrmal** [comment]
@danpovey is this resolved by #26? Or is there any outstanding work to be
done?

**Comment by danpovey** [comment]
I have done it locally, will push soon

**Comment by danpovey** [comment]
Resolved by #26
